/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStockInventoryRouteImport } from './routes/_authenticated/stock-inventory'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedProductionReportRouteImport } from './routes/_authenticated/production-report'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProFormRouteImport } from './routes/_authenticated/pro-form'
import { Route as AuthenticatedPrintingRouteImport } from './routes/_authenticated/printing'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedManagingDirectorRouteImport } from './routes/_authenticated/managing-director'
import { Route as AuthenticatedIngredientUsageRouteImport } from './routes/_authenticated/ingredient-usage'
import { Route as AuthenticatedFactorySalesRouteImport } from './routes/_authenticated/factory-sales'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCashSummaryRouteImport } from './routes/_authenticated/cash-summary'
import { Route as AuthenticatedCashFlowByPersonRouteImport } from './routes/_authenticated/cash-flow-by-person'
import { Route as AuthenticatedCashFlowRouteImport } from './routes/_authenticated/cash-flow'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockInventoryRoute =
  AuthenticatedStockInventoryRouteImport.update({
    id: '/stock-inventory',
    path: '/stock-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionReportRoute =
  AuthenticatedProductionReportRouteImport.update({
    id: '/production-report',
    path: '/production-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProFormRoute = AuthenticatedProFormRouteImport.update({
  id: '/pro-form',
  path: '/pro-form',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintingRoute = AuthenticatedPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagingDirectorRoute =
  AuthenticatedManagingDirectorRouteImport.update({
    id: '/managing-director',
    path: '/managing-director',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIngredientUsageRoute =
  AuthenticatedIngredientUsageRouteImport.update({
    id: '/ingredient-usage',
    path: '/ingredient-usage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFactorySalesRoute =
  AuthenticatedFactorySalesRouteImport.update({
    id: '/factory-sales',
    path: '/factory-sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashSummaryRoute =
  AuthenticatedCashSummaryRouteImport.update({
    id: '/cash-summary',
    path: '/cash-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashFlowByPersonRoute =
  AuthenticatedCashFlowByPersonRouteImport.update({
    id: '/cash-flow-by-person',
    path: '/cash-flow-by-person',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashFlowRoute = AuthenticatedCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/cash-flow': typeof AuthenticatedCashFlowRoute
  '/cash-flow-by-person': typeof AuthenticatedCashFlowByPersonRoute
  '/cash-summary': typeof AuthenticatedCashSummaryRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/factory-sales': typeof AuthenticatedFactorySalesRoute
  '/ingredient-usage': typeof AuthenticatedIngredientUsageRoute
  '/managing-director': typeof AuthenticatedManagingDirectorRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/printing': typeof AuthenticatedPrintingRoute
  '/pro-form': typeof AuthenticatedProFormRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-report': typeof AuthenticatedProductionReportRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/stock-inventory': typeof AuthenticatedStockInventoryRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/cash-flow': typeof AuthenticatedCashFlowRoute
  '/cash-flow-by-person': typeof AuthenticatedCashFlowByPersonRoute
  '/cash-summary': typeof AuthenticatedCashSummaryRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/factory-sales': typeof AuthenticatedFactorySalesRoute
  '/ingredient-usage': typeof AuthenticatedIngredientUsageRoute
  '/managing-director': typeof AuthenticatedManagingDirectorRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/printing': typeof AuthenticatedPrintingRoute
  '/pro-form': typeof AuthenticatedProFormRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-report': typeof AuthenticatedProductionReportRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/stock-inventory': typeof AuthenticatedStockInventoryRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/cash-flow': typeof AuthenticatedCashFlowRoute
  '/_authenticated/cash-flow-by-person': typeof AuthenticatedCashFlowByPersonRoute
  '/_authenticated/cash-summary': typeof AuthenticatedCashSummaryRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/factory-sales': typeof AuthenticatedFactorySalesRoute
  '/_authenticated/ingredient-usage': typeof AuthenticatedIngredientUsageRoute
  '/_authenticated/managing-director': typeof AuthenticatedManagingDirectorRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/printing': typeof AuthenticatedPrintingRoute
  '/_authenticated/pro-form': typeof AuthenticatedProFormRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/production-report': typeof AuthenticatedProductionReportRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/stock-inventory': typeof AuthenticatedStockInventoryRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/audit-log'
    | '/cash-flow'
    | '/cash-flow-by-person'
    | '/cash-summary'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/factory-sales'
    | '/ingredient-usage'
    | '/managing-director'
    | '/materials'
    | '/printing'
    | '/pro-form'
    | '/production'
    | '/production-report'
    | '/reconciliation'
    | '/reports'
    | '/sales'
    | '/stock-inventory'
    | '/agents/$id'
    | '/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agents'
    | '/audit-log'
    | '/cash-flow'
    | '/cash-flow-by-person'
    | '/cash-summary'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/factory-sales'
    | '/ingredient-usage'
    | '/managing-director'
    | '/materials'
    | '/printing'
    | '/pro-form'
    | '/production'
    | '/production-report'
    | '/reconciliation'
    | '/reports'
    | '/sales'
    | '/stock-inventory'
    | '/agents/$id'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/audit-log'
    | '/_authenticated/cash-flow'
    | '/_authenticated/cash-flow-by-person'
    | '/_authenticated/cash-summary'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/factory-sales'
    | '/_authenticated/ingredient-usage'
    | '/_authenticated/managing-director'
    | '/_authenticated/materials'
    | '/_authenticated/printing'
    | '/_authenticated/pro-form'
    | '/_authenticated/production'
    | '/_authenticated/production-report'
    | '/_authenticated/reconciliation'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/stock-inventory'
    | '/_authenticated/agents/$id'
    | '/_authenticated/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock-inventory': {
      id: '/_authenticated/stock-inventory'
      path: '/stock-inventory'
      fullPath: '/stock-inventory'
      preLoaderRoute: typeof AuthenticatedStockInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-report': {
      id: '/_authenticated/production-report'
      path: '/production-report'
      fullPath: '/production-report'
      preLoaderRoute: typeof AuthenticatedProductionReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro-form': {
      id: '/_authenticated/pro-form'
      path: '/pro-form'
      fullPath: '/pro-form'
      preLoaderRoute: typeof AuthenticatedProFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printing': {
      id: '/_authenticated/printing'
      path: '/printing'
      fullPath: '/printing'
      preLoaderRoute: typeof AuthenticatedPrintingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/managing-director': {
      id: '/_authenticated/managing-director'
      path: '/managing-director'
      fullPath: '/managing-director'
      preLoaderRoute: typeof AuthenticatedManagingDirectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingredient-usage': {
      id: '/_authenticated/ingredient-usage'
      path: '/ingredient-usage'
      fullPath: '/ingredient-usage'
      preLoaderRoute: typeof AuthenticatedIngredientUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factory-sales': {
      id: '/_authenticated/factory-sales'
      path: '/factory-sales'
      fullPath: '/factory-sales'
      preLoaderRoute: typeof AuthenticatedFactorySalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-summary': {
      id: '/_authenticated/cash-summary'
      path: '/cash-summary'
      fullPath: '/cash-summary'
      preLoaderRoute: typeof AuthenticatedCashSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-flow-by-person': {
      id: '/_authenticated/cash-flow-by-person'
      path: '/cash-flow-by-person'
      fullPath: '/cash-flow-by-person'
      preLoaderRoute: typeof AuthenticatedCashFlowByPersonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-flow': {
      id: '/_authenticated/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AuthenticatedCashFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedCashFlowRoute: typeof AuthenticatedCashFlowRoute
  AuthenticatedCashFlowByPersonRoute: typeof AuthenticatedCashFlowByPersonRoute
  AuthenticatedCashSummaryRoute: typeof AuthenticatedCashSummaryRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFactorySalesRoute: typeof AuthenticatedFactorySalesRoute
  AuthenticatedIngredientUsageRoute: typeof AuthenticatedIngredientUsageRoute
  AuthenticatedManagingDirectorRoute: typeof AuthenticatedManagingDirectorRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedPrintingRoute: typeof AuthenticatedPrintingRoute
  AuthenticatedProFormRoute: typeof AuthenticatedProFormRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductionReportRoute: typeof AuthenticatedProductionReportRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedStockInventoryRoute: typeof AuthenticatedStockInventoryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedCashFlowRoute: AuthenticatedCashFlowRoute,
  AuthenticatedCashFlowByPersonRoute: AuthenticatedCashFlowByPersonRoute,
  AuthenticatedCashSummaryRoute: AuthenticatedCashSummaryRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFactorySalesRoute: AuthenticatedFactorySalesRoute,
  AuthenticatedIngredientUsageRoute: AuthenticatedIngredientUsageRoute,
  AuthenticatedManagingDirectorRoute: AuthenticatedManagingDirectorRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedPrintingRoute: AuthenticatedPrintingRoute,
  AuthenticatedProFormRoute: AuthenticatedProFormRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductionReportRoute: AuthenticatedProductionReportRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedStockInventoryRoute: AuthenticatedStockInventoryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
