/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedCashFlowRouteImport } from './routes/_authenticated/cash-flow'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedIngredientUsageRouteImport } from './routes/_authenticated/ingredient-usage'
import { Route as AuthenticatedManagingDirectorRouteImport } from './routes/_authenticated/managing-director'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedPrintingRouteImport } from './routes/_authenticated/printing'
import { Route as AuthenticatedProFormRouteImport } from './routes/_authenticated/pro-form'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashFlowRoute = AuthenticatedCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIngredientUsageRoute =
  AuthenticatedIngredientUsageRouteImport.update({
    id: '/ingredient-usage',
    path: '/ingredient-usage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagingDirectorRoute =
  AuthenticatedManagingDirectorRouteImport.update({
    id: '/managing-director',
    path: '/managing-director',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintingRoute = AuthenticatedPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProFormRoute = AuthenticatedProFormRouteImport.update({
  id: '/pro-form',
  path: '/pro-form',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/cash-flow': typeof AuthenticatedCashFlowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/ingredient-usage': typeof AuthenticatedIngredientUsageRoute
  '/managing-director': typeof AuthenticatedManagingDirectorRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/printing': typeof AuthenticatedPrintingRoute
  '/pro-form': typeof AuthenticatedProFormRoute
  '/production': typeof AuthenticatedProductionRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/cash-flow': typeof AuthenticatedCashFlowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/ingredient-usage': typeof AuthenticatedIngredientUsageRoute
  '/managing-director': typeof AuthenticatedManagingDirectorRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/printing': typeof AuthenticatedPrintingRoute
  '/pro-form': typeof AuthenticatedProFormRoute
  '/production': typeof AuthenticatedProductionRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/cash-flow': typeof AuthenticatedCashFlowRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/ingredient-usage': typeof AuthenticatedIngredientUsageRoute
  '/_authenticated/managing-director': typeof AuthenticatedManagingDirectorRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/printing': typeof AuthenticatedPrintingRoute
  '/_authenticated/pro-form': typeof AuthenticatedProFormRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/cash-flow'
    | '/dashboard'
    | '/expenses'
    | '/ingredient-usage'
    | '/managing-director'
    | '/materials'
    | '/printing'
    | '/pro-form'
    | '/production'
    | '/reconciliation'
    | '/reports'
    | '/sales'
    | '/agents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agents'
    | '/cash-flow'
    | '/dashboard'
    | '/expenses'
    | '/ingredient-usage'
    | '/managing-director'
    | '/materials'
    | '/printing'
    | '/pro-form'
    | '/production'
    | '/reconciliation'
    | '/reports'
    | '/sales'
    | '/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/cash-flow'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/ingredient-usage'
    | '/_authenticated/managing-director'
    | '/_authenticated/materials'
    | '/_authenticated/printing'
    | '/_authenticated/pro-form'
    | '/_authenticated/production'
    | '/_authenticated/reconciliation'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/agents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-flow': {
      id: '/_authenticated/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AuthenticatedCashFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingredient-usage': {
      id: '/_authenticated/ingredient-usage'
      path: '/ingredient-usage'
      fullPath: '/ingredient-usage'
      preLoaderRoute: typeof AuthenticatedIngredientUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/managing-director': {
      id: '/_authenticated/managing-director'
      path: '/managing-director'
      fullPath: '/managing-director'
      preLoaderRoute: typeof AuthenticatedManagingDirectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printing': {
      id: '/_authenticated/printing'
      path: '/printing'
      fullPath: '/printing'
      preLoaderRoute: typeof AuthenticatedPrintingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro-form': {
      id: '/_authenticated/pro-form'
      path: '/pro-form'
      fullPath: '/pro-form'
      preLoaderRoute: typeof AuthenticatedProFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedCashFlowRoute: typeof AuthenticatedCashFlowRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedIngredientUsageRoute: typeof AuthenticatedIngredientUsageRoute
  AuthenticatedManagingDirectorRoute: typeof AuthenticatedManagingDirectorRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedPrintingRoute: typeof AuthenticatedPrintingRoute
  AuthenticatedProFormRoute: typeof AuthenticatedProFormRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedCashFlowRoute: AuthenticatedCashFlowRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedIngredientUsageRoute: AuthenticatedIngredientUsageRoute,
  AuthenticatedManagingDirectorRoute: AuthenticatedManagingDirectorRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedPrintingRoute: AuthenticatedPrintingRoute,
  AuthenticatedProFormRoute: AuthenticatedProFormRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
